version: "3.8"

services:
    mysql:
        image: mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - '--character-set-server=utf8'
        restart: "no"
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - app-dbdata:/var/lib/mysql
            - ./../../../ops/docker/mysql/my.cnf:/etc/mysql/my.cnf
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        command: redis-server
        restart: "no"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    app-dbdata:
        driver: local
